// import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@csstools/normalize.css';
import Header from '@/components/header';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  //TODO ここにHTMLの構造を書いていく
  return (
    <html lang="en">
      <head />
      <body className={inter.className}>
        <Header />
        {children}
        <footer>Footer</footer>
        </body>
    </html>
  )
}
